### ISSUE TITLE
Trouble reproducing Jansen-Rit model dynamics in current version

### ISSUE THREAD

**Issue by ffriese** [pyrates-neuroscience/PyRates#25]
Dear PyRates developers,
first off, I want to say that I really like PyRates for its versatility and simple usage- so thanks a lot for creating it!

That being said, I have been trying to reproduce findings from [David and Friston (2003)](https://doi.org/10.1016/j.neuroimage.2003.07.015), but ran into trouble getting the expected results with the newest version of PyRates.

[This Jupyter Notebook included with PyRates (**Simulation 2: Jansen-Rit model sensitivity to changes in the synaptic timescales**)](https://github.com/pyrates-neuroscience/PyRates/blob/master/documentation/JansenRit_model_dynamics.ipynb), appears to reproduce [Fig. 4](https://ars.els-cdn.com/content/image/1-s2.0-S1053811903004579-gr4.sml) from the paper quite well (as also stated in the [PyRates paper]( https://doi.org/10.1371/journal.pone.0225900
)), but when I try to run it with the current master (after adapting a few lines to make it execute without complaining - more on that below), it produces different output:

### Figures

Output-Figure included in .ipynb-File| Result when running with current master
------------ | -------------
![pyrates_jupyter](https://user-images.githubusercontent.com/28440404/104814724-cbfcde80-5810-11eb-9fdb-38aef694aa2a.png) | ![pyrates_newest](https://user-images.githubusercontent.com/28440404/104813074-137e6d00-5807-11eb-8659-e05d1768aeb9.png)
reproduces David and Friston (2003) Fig. 4 | produces different data

### Necessary changes
The changes required to execute the notebook-code with the current version were limited to the following:
 ``` diff
results, params = grid_search(circuit_template="model_templates.jansen_rit.simple_jansenrit.JRC",
                              param_grid=params, param_map=param_map,
                              inputs={"PC/RPO_e_pc/u": inp}, outputs={"v": "PC/OBS/V"},
-                            dt=dt,
+                            step_size=dt, 
                              simulation_time=T, permute_grid=False, sampling_step_size=dts)
```

as well as

``` diff
- freqs, power = fft(results[key], tmin=cut_off)
+ from pandas import DataFrame
+ freqs, power = fft(DataFrame(results[('v', key, 'PC')]), tmin=cut_off)
```
and, to make the graph more comparable (y-axis flip)
``` diff
- tau_i = np.arange(1e-3, 63e-3, 5e-3)
+ tau_i = np.flip(np.arange(1e-3, 63e-3, 5e-3)) 
```

### Steps taken so far
To investigate whether (and if so, at what point in the commit-history) the framework did actually produce the given plot, and to rule out that any updated dependencies may be the root of the problem, I checked out the newest commit that included the string `notebook` in its commit message.

This happend to be c97e8ba06b3c04ec5b55f2cdba5a8b28d73db5fb, and indeed (after applying the same `np.flip` adaption) it easily produces the following graph:
Result when running with c97e8ba06b3c04ec5b55f2cdba5a8b28d73db5fb |
------------ |
![old-commit](https://user-images.githubusercontent.com/28440404/104817625-ad074800-5822-11eb-9f22-5f1b4fb75dab.png)|
appears to be working correctly (minimal differences due to random input)|

This must mean that somewhere since this commit, a change has been introduced that ever so slightly changes the behavior of the simple Jansen-Rit Model Circuit. 
Interestingly enough, the properties of the signals that are produced within the usual ranges (&tau;<sub>i</sub> = 20ms, &tau;<sub>e</sub> = 10ms) do not change enough to cause noticable problems when reproducing other widely analysed features of the Jansen-Rit Model (e.g. the first part of the Jupyter Notebook).

As I have only recently started to dig into the deeper sections of the PyRates Code, I do not have any idea what kind of alteration may have caused such a subtle change, so I will probably start to try to single out the commit that introduces this change.

In the meantime, I would be glad if anybody could point me into the right direction.

### Additional (possibly consequent?) problems
This change in behavior **might** also be responsible for the issue that made me aware of the problem in the first place:

When trying to reproduce [Fig. 5](https://ars.els-cdn.com/content/image/1-s2.0-S1053811903004579-gr5.sml) from the David and Friston paper, which required some minor changes to the model as well, I get the following result, which shows clear peaks in all conditions, while only the first and last are expected and all the other conditions should produce much more noisy, wider distributions:

Attempt to reproduce Fig. 5 from David and Friston |
------------ |
![fig5](https://user-images.githubusercontent.com/28440404/104817861-5b5fbd00-5824-11eb-9420-168f28de5181.png)|

While it is entirely possible that there is an issue in my modification to the model that causes this, I have not yet gotten around to fix the compatibilty-errors that prevent me from running my newer implementations on the c97e8ba06b3c04ec5b55f2cdba5a8b28d73db5fb version and testing whether it works as expected there. 

To keep this issue fairly simple, I wanted to put the focus on the more obvious problem first (which, on solution, might even fix this alltogether) - but again, I would be happy to get any insights on this as well, and will gladly provide and explain my code if anybody is interested in figuring this out with me.

Thanks in advance

**Comment by Richert** [comment]
Dear @ffriese ,

thanks so much for your interest in our toolbox, we really appreciate you working with it and helping to improve it.

In response to your comments, I pushed an update to the master. As part of that update, I used some of your suggested changes to the code and made some changes to it myself.  Most importantly, I changed the definition of the output variables (see commit notes). On my system, the current version of the notebook reproduces Fig. 4 of the PloS One paper exactly. Can you confirm that this is the case for you as well? 

As a general comment, I recommend to only define variables as output variables, whose dynamics are governed by differential equations in the model definition. This is, because these are the actual system or state variables, which we track in the backend. Other helper variables are treated differently and so far we have not ensured that tracking them as output variables produces stable, desired behavior. I believe that this is what caused the difference. Can you confirm that?

Regarding your other issue with reproducing Fig. 5 of David and Friston (2003), I would be interested in the changes of the model set up that you used. Maybe, implementing the changes I suggest above already help? Apart from that there are 2 things that could easily go wrong here:

(1) The re-scaling of the synaptic efficacies with the synaptic time constants in the model. In the following snippet from [https://github.com/pyrates-neuroscience/PyRates/blob/master/documentation/JansenRit_model_dynamics.ipynb](url), I perform a different re-scaling of the synaptic efficacies than the one that David and Friston describe in their paper. This is simply, because they made a mistake in their manuscript. So you should use these re-scalings to set up the multi-population model.

```
for t_e in tau_e:

    for t_i in tau_i:

        params['tau_e'].append(t_e)                               
        params['tau_i'].append(t_i)
        params['H_e'].append(3.25e-3*10e-3/t_e)                                
        params['H_i'].append(-22e-3*20e-3/t_i)
```

(2) When changing the integration time-constant (`step_size`), this also changes the effective variance in the noisy, extrinsic input applied to the network, so you should be careful with that. One way to prevent this, is to define the noisy input in the desired time resolution (e.g. dor `step_size = 1e-4`), but then choose the variable step-size solver in PyRates.
This you can do via the following:

```
from pyrates.frontend import CircuitTemplate
jrc = CircuitTemplate.from_yaml("model_templates.jansen_rit.simple_jansenrit.JRC_simple").apply()
jrc_compiled = jrc.compile(backend='numpy', step_size=1e-4, solver='scipy')

results = jrc_compiled.run(simulation_time=2.0,
                           step_size=1e-4,
                           sampling_step_size=1e-3,
                           outputs={'V_pce': 'JRC/JRC_op/PSP_pc_e',
                                    'V_pci': 'JRC/JRC_op/PSP_pc_i'})
```

Choosing the solver and backend in the `compile` method is the critical step there. This is described in a bit more detail in [https://github.com/pyrates-neuroscience/PyRates/blob/master/documentation/model_introduction/jansenrit.py](url).
To do this in a `grid_search` call, simply use the following syntax:

```
from pyrates.utility.grid_search import grid_search
param_grid = {'C': [68., 128., 135., 270., 675., 1350.]}
param_map = {'C': {'vars': ['JRC_op/c'], 'nodes': ['JRC']}}

results, results_map = grid_search(circuit_template="model_templates.jansen_rit.simple_jansenrit.JRC_simple",
                                   param_grid=param_grid,
                                   param_map=param_map,
                                   simulation_time=10.0,
                                   step_size=1e-4,
                                   sampling_step_size=1e-3,
                                   inputs={},
                                   outputs={'V_pce': 'JRC/JRC_op/PSP_pc_e', 'V_pci': 'JRC/JRC_op/PSP_pc_i'},
                                   init_kwargs={'backend': 'numpy', 'solver': 'scipy'}
                                   )
```

Where I provided the critical information via the keyword argument `init_kwargs`.
Let me know whether this helps. If not, I am happy to help to reproduce that Fig. 5 correctly.

**Comment by ffriese** [comment]
Dear @Richert,
thanks a lot for the quick effort to resolve my problems and the extensive response.
I am really looking forward to trying it out tomorrow and letting you know how it went.

(Regarding your suggestion (1), I already want to say that this hint would have saved me hours of frustation at the time I implemented my modifications - before I then actually found the solution **in your notebook** - so thanks for that as well!)

**Comment by ffriese** [comment]
I finally got around to test your update, and indeed the changes (your idea about the output variable definition being the culprit sounds reasonable to me) lead to a perfect reproduction of Figure 4 🎉 
Thanks again for your quick help!

My other problem was unfortunately not resolved by this, as I do not use any observer operator and manually add the resulting population potentials at the end of the run.

However, changing the solver from `euler` back to `scipy` (apparently while trying to overcome other performance-related issues, I had played around with this too much without having a deeper understanding of all implications) *did* make a slight difference (see below).
Switching the `step_size` between `1e-3` and `1e-4` while keeping the `sampling_step_size` at  `1e-3` did not noticeably change anything after that.

Using `scipy` as solver|
------------------------|
![fig5_dt1e3scipy](https://user-images.githubusercontent.com/28440404/105091435-1d6ecd00-5aa0-11eb-9c38-37ec9de6458c.png)|

This seems to go into the right direction, but the signals do not yet reach the same level of noise as they do in the original Figure:
[Fig.5](https://ars.els-cdn.com/content/image/1-s2.0-S1053811903004579-gr5.sml)|
------------------------|
![https://ars.els-cdn.com/content/image/1-s2.0-S1053811903004579-gr5.sml](https://ars.els-cdn.com/content/image/1-s2.0-S1053811903004579-gr5.sml)|

I will compile a minimal code snippet to reproduce this as soon as I find enough time in the next couple of days - I do not want to just paste all of my (somewhat messy) experimental code here.
Thanks for your support!

**Comment by ffriese** [comment]
Today I finally found time to stitch together a somewhat clean code-snippet that produces the graph I posted above.

My interpretation of the descriptions in the paper was, 
that I simply needed to split the equation `d/dt * I = H/tau * m_in - (1./tau)^2. * PSP - 2. * 1./tau * I` in the RPO into two parts to represent each subpopulation and mix those together according to `w` when calculating the PSP.

Maybe I already missed a detail at that point, or I have some misconception on how to do this correctly in PyRates.
Thanks in advance for having a look at it.

```python
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal

from pyrates.frontend import OperatorTemplate, NodeTemplate, CircuitTemplate
from pyrates.utility.grid_search import grid_search


def create_pro(name):
    return OperatorTemplate(
        name=name, path='',
        equations=["m_out = m_max / (1 + exp(r*(V_thr - PSP)))"],
        variables={'m_out': {'default': 'output'},
                   'PSP': {'default': 'input'},
                   'V_thr': {'default': 6e-3},
                   'm_max': {'default': 5.},
                   'r': {'default': 560.0}},
        description="sigmoidal potential-to-rate operator")


def create_rpo(name, tau_0, tau_1, h_0, h_1):
    return OperatorTemplate(
        name=name, path='',
        equations=['d/dt * PSP = (w_0 * I_0) + (w_1 * I_1)',
                   'd/dt * I_0 = H_0/tau_0 * m_in - (1./tau_0)^2. * PSP - 2. * 1./tau_0 * I_0',
                   'd/dt * I_1 = H_1/tau_1 * m_in - (1./tau_1)^2. * PSP - 2. * 1./tau_1 * I_1'],
        variables={'PSP': {'default': 'output'},
                   'I_0': {'default': 'variable'},
                   'I_1': {'default': 'variable'},
                   'm_in': {'default': 'input'},
                   'w_0': {'default': 1.0},
                   'w_1': {'default': 0.0},
                   'tau_0': {'default': tau_0},
                   'tau_1': {'default': tau_1},
                   'H_0': {'default': h_0},
                   'H_1': {'default': h_1}},
        description="rate-to-potential operator")


def subpopulation_model():
    """
        Creates a Jansen-Rit Circuit with two subpopulations in each rate-to-potential operator
         as proposed by David and Friston
    """
    pro = create_pro(name='PRO')
    pro_pc = create_pro(name='PRO_pc')

    # subpopulation parameters taken from the paper
    tau_e = [10.8e-3, 4.6e-3]
    tau_i = [22e-3, 2.9e-3]

    h_e = [3.25e-3 * 10e-3 / tau for tau in tau_e]
    h_i = [-22e-3 * 20e-3 / tau for tau in tau_i]

    rpo_e = create_rpo('RPO_e', tau_e[0], tau_e[1], h_e[0], h_e[1])
    rpo_e_pc = rpo_e.update_template('RPO_e_pc', '', equations={'replace': {'m_in': '(m_in+u)'}},
                                     variables={'u': {'default': 220.0}})
    rpo_i = create_rpo('RPO_i', tau_i[0], tau_i[1], h_i[0], h_i[1])

    ein = NodeTemplate(name="EIN", path='', operators=[pro, rpo_e])
    iin = NodeTemplate(name="IIN", path='', operators=[pro, rpo_e])
    pc = NodeTemplate(name="PC", path='', operators=[pro_pc, rpo_e_pc, rpo_i])

    jrc = CircuitTemplate(
        name="JRC", nodes={'PC': pc, 'EIN': ein, 'IIN': iin},
        edges=[
               ("PC/PRO_pc/m_out", "EIN/RPO_e/m_in", None, {'weight': 135.}),
               ("EIN/PRO/m_out", "PC/RPO_e_pc/m_in", None, {'weight': 108.}),
               ("PC/PRO_pc/m_out", "IIN/RPO_e/m_in", None, {'weight': 33.75}),
               ("IIN/PRO/m_out", "PC/RPO_i/m_in", None, {'weight': 33.75})],
        path='')
    return jrc


def simulate(template, step_size, sampling_step_size, seconds, cutoff):
    """
        Performs a grid search for w (mix the subpopulations)
    """
    ws = np.arange(0, 1.2, 0.2)
    param_grid = {
        'w_0': [round(w, 1) for w in ws],
        'w_1': [round(1-w, 1) for w in ws],
    }
    param_map = {
        'w_0': {
            'vars': ['RPO_e/w_0',
                     'RPO_e_pc/w_0',
                     'RPO_i/w_0'], 'nodes': ['PC', 'EIN', 'IIN']},
        'w_1': {
            'vars': ['RPO_e/w_1',
                     'RPO_e_pc/w_1',
                     'RPO_i/w_1'], 'nodes': ['PC', 'EIN', 'IIN']},
    }
    size = (int(np.round(seconds / step_size, decimals=0)), 1)

    res, results_map = grid_search(circuit_template=template,
                                   param_grid=param_grid,
                                   param_map=param_map,
                                   simulation_time=seconds,
                                   step_size=step_size,
                                   sampling_step_size=sampling_step_size,
                                   inputs={'PC/RPO_e_pc/u': np.random.normal(loc=220.0, scale=22.0, size=size)},
                                   outputs={'V_pce': 'PC/RPO_e_pc/PSP', 'V_pci': 'PC/RPO_i/PSP'},
                                   init_kwargs={'backend': 'numpy', 'solver': 'scipy'},
                                   verbose=False)
    results = res['V_pce'] + res['V_pci']
    results = results.loc[cutoff:]
    return results, results_map, sampling_step_size


def plot(results, results_map, sampling_step_size):
    """
        Plot the resulting signals and their spectrum
    """
    fig = plt.figure(figsize=(8, 12))
    fig.suptitle('David and Friston (2003) Fig.5')
    gs = fig.add_gridspec(len(results_map), 2)

    def periodogram(data, fs, freq_range):
        _f, power = scipy.signal.periodogram(data, fs)
        selection = np.where((freq_range[0] <= _f) & (_f <= freq_range[1]))
        f = _f[selection]
        power = power[selection]
        return f, power

    for row, (r, v) in enumerate(results.items()):
        v_lb = [f'${key} = {results_map.at[r[0], key]}$' for key in results_map.columns]
        ax = fig.add_subplot(gs[row, 0])
        ax.plot(results.index, v, label=", ".join(v_lb), color=f'C{row}')
        ax.legend(loc='upper right')

        ax2 = fig.add_subplot(gs[row, 1])
        ax2.plot(*periodogram(data=v, fs=1/sampling_step_size, freq_range=(0, 100)),
                 label=', '.join(v_lb), color=f'C{row}')
        ax2.legend(loc='upper right')
        row += 1
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    plot(*simulate(template=subpopulation_model(), 
                   step_size=1e-4,  # choosing 1e-3 here does not really make a difference
                   sampling_step_size=1e-3,
                   seconds=2.0, cutoff=1.0))

```

**Comment by Richert** [comment]
Hello @ffriese ,

I had a look at your code today and identified the problem(s). First of all, you were right in your interpretation that the synaptic convolution operators (RPOs) simply need to be split into two and that the `PSP` is calculated via a combination of the two different synaptic activations via `w_0` and `w_1`. However, in the above equations, the alpha kernel convolutions are not expressed correctly anymore. Each synaptic activation at a given RPO needs to be defined via two coupled differential equations. If you have two different synaptic operators, you will need 4 differential equations in total.

I put together a working example below:

An additional thing that I fixed is the definition of the PSP. In your code, it is defined via a differential equation that has an implicit time constant of 1. This effectively smoothed out your PSP traces, making them less noisy than in the original figure by David and Friston (2003). In the code below, I defined `PSP` to be governed by a simple (non-differential) equation and used the synaptic activations as output variables, so that I can combine them to the final membrane potential `v` before plotting.

Hope that helps! Since this solves the issue on my system, I will close the issue for now. Let me know, if there are still issues left.

Best, Richard

```
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal

from pyrates.frontend import OperatorTemplate, NodeTemplate, CircuitTemplate
from pyrates.utility.grid_search import grid_search


def create_pro(name):
    return OperatorTemplate(
        name=name, path='',
        equations=["m_out = m_max / (1 + exp(r*(V_thr - PSP)))"],
        variables={'m_out': {'default': 'output'},
                   'PSP': {'default': 'input'},
                   'V_thr': {'default': 6e-3},
                   'm_max': {'default': 5.},
                   'r': {'default': 560.0}},
        description="sigmoidal potential-to-rate operator")


def create_rpo(name, tau_0, tau_1, h_0, h_1):
    return OperatorTemplate(
        name=name, path='',
        equations=['d/dt * I_0 = X_0',
                   'd/dt * X_0 = H_0/tau_0 * m_in - (1./tau_0)^2. * I_0 - 2. * 1./tau_0 * X_0',
                   'd/dt * I_1 = X_1',
                   'd/dt * X_1 = H_1/tau_1 * m_in - (1./tau_1)^2. * I_1 - 2. * 1./tau_1 * X_1',
                   'PSP = w_0*I_0 + w_1*I_1'],
        variables={'PSP': {'default': 'output'},
                   'I_0': {'default': 'variable'},
                   'I_1': {'default': 'variable'},
                   'X_0': {'default': 'variable'},
                   'X_1': {'default': 'variable'},
                   'm_in': {'default': 'input'},
                   'w_0': {'default': 1.0},
                   'w_1': {'default': 0.0},
                   'tau_0': {'default': tau_0},
                   'tau_1': {'default': tau_1},
                   'H_0': {'default': h_0},
                   'H_1': {'default': h_1}},
        description="rate-to-potential operator")


def subpopulation_model():
    """
        Creates a Jansen-Rit Circuit with two subpopulations in each rate-to-potential operator
         as proposed by David and Friston
    """
    pro = create_pro(name='PRO')
    pro_pc = create_pro(name='PRO_pc')

    # subpopulation parameters taken from the paper
    tau_e = [10.8e-3, 4.6e-3]
    tau_i = [22e-3, 2.9e-3]

    h_e = [3.25e-3 * 10e-3 / tau for tau in tau_e]
    h_i = [-22e-3 * 20e-3 / tau for tau in tau_i]

    rpo_e = create_rpo('RPO_e', tau_e[0], tau_e[1], h_e[0], h_e[1])
    rpo_e_pc = rpo_e.update_template('RPO_e_pc', '', equations={'replace': {'m_in': '(m_in+u)'}},
                                     variables={'u': {'default': 220.0}})
    rpo_i = create_rpo('RPO_i', tau_i[0], tau_i[1], h_i[0], h_i[1])

    ein = NodeTemplate(name="EIN", path='', operators=[pro, rpo_e])
    iin = NodeTemplate(name="IIN", path='', operators=[pro, rpo_e])
    pc = NodeTemplate(name="PC", path='', operators=[pro_pc, rpo_e_pc, rpo_i])

    jrc = CircuitTemplate(
        name="JRC", nodes={'PC': pc, 'EIN': ein, 'IIN': iin},
        edges=[
               ("PC/PRO_pc/m_out", "EIN/RPO_e/m_in", None, {'weight': 135.}),
               ("EIN/PRO/m_out", "PC/RPO_e_pc/m_in", None, {'weight': 108.}),
               ("PC/PRO_pc/m_out", "IIN/RPO_e/m_in", None, {'weight': 33.75}),
               ("IIN/PRO/m_out", "PC/RPO_i/m_in", None, {'weight': 33.75})],
        path='')
    return jrc


def simulate(template, step_size, sampling_step_size, seconds, cutoff):
    """
        Performs a grid search for w (mix the subpopulations)
    """
    ws = np.arange(0, 1.1, 0.2)
    param_grid = {
        'w_0': [round(w, 1) for w in ws],
        'w_1': [round(1-w, 1) for w in ws],
    }
    param_map = {
        'w_0': {
            'vars': ['RPO_e/w_0',
                     'RPO_e_pc/w_0',
                     'RPO_i/w_0'], 'nodes': ['PC', 'EIN', 'IIN']},
        'w_1': {
            'vars': ['RPO_e/w_1',
                     'RPO_e_pc/w_1',
                     'RPO_i/w_1'], 'nodes': ['PC', 'EIN', 'IIN']},
    }
    size = (int(np.round(seconds / step_size, decimals=0)), 1)

    results, results_map = grid_search(circuit_template=template,
                                       param_grid=param_grid,
                                       param_map=param_map,
                                       simulation_time=seconds,
                                       step_size=step_size,
                                       sampling_step_size=sampling_step_size,
                                       inputs={'PC/RPO_e_pc/u': np.random.normal(loc=220.0, scale=22.0, size=size)},
                                       outputs={'I0_pce': 'PC/RPO_e_pc/I_0', 'I1_pce': 'PC/RPO_e_pc/I_1',
                                                'I0_pci': 'PC/RPO_i/I_0', 'I1_pci': 'PC/RPO_i/I_1'},
                                       init_kwargs={'backend': 'numpy', 'solver': 'scipy'},
                                       verbose=False,
                                       permute_grid=False)
    results = results.loc[cutoff:]
    return results, results_map, sampling_step_size


def plot(results, results_map, sampling_step_size):
    """
        Plot the resulting signals and their spectrum
    """
    fig = plt.figure(figsize=(8, 12))
    fig.suptitle('David and Friston (2003) Fig.5')
    gs = fig.add_gridspec(len(results_map), 2)

    def periodogram(data, fs, freq_range):
        _f, power = scipy.signal.periodogram(data, fs)
        selection = np.where((freq_range[0] <= _f) & (_f <= freq_range[1]))
        f = _f[selection]
        power = power[selection]
        return f, power

    for row, key in enumerate(results_map.index):

        # get infos from results map
        ws = [results_map.at[key, c] for c in results_map.columns]
        v_lb = [f'${key} = {w}$' for key, w in zip(results_map.columns, ws)]

        # calculate combined LFP
        psp_0 = results.loc[:, ('I0_pce', key)] + results.loc[:, ('I0_pci', key)]
        psp_1 = results.loc[:, ('I1_pce', key)] + results.loc[:, ('I1_pci', key)]
        v = psp_0*ws[0] + psp_1*ws[1]
        ax = fig.add_subplot(gs[row, 0])
        ax.plot(results.index, v, label=", ".join(v_lb), color=f'C{row}')
        ax.legend(loc='upper right')

        ax2 = fig.add_subplot(gs[row, 1])
        ax2.plot(*periodogram(data=np.squeeze(v.values), fs=1/sampling_step_size, freq_range=(0, 100)),
                 label=', '.join(v_lb), color=f'C{row}')
        ax2.legend(loc='upper right')
        row += 1
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    plot(*simulate(template=subpopulation_model(),
                   step_size=1e-4,  # choosing 1e-3 here does not really make a difference
                   sampling_step_size=1e-3,
                   seconds=2.0, cutoff=1.0))

```

**Comment by ffriese** [comment]
Hello @Richert,

first off, sorry for my late reply, I've been somewhat busy in the last week.

Your changes to my code indeed helped a lot, I obviously had some issues correctly understanding these coupled equations,
but it does make sense to me now.

My current results (averaged over 10 runs, as described in the paper) are attached below, and are really quite close to the original Figure, covering similar spectral ranges and having similar peaks.

Visually, the spectrum still does look a bit different (I have substantially more variance in the amplitude, whereas their curves are somewhat smoother) - I am not sure whether this may also be due to a difference in spectral density estimation, as I did not find any specifics to their method in the paper.

When I changed from `scipy.signal.periodogram` to `np.fft.fft`, the plot did get somewhat closer to the original, and after one specific batch-run, I got a particularly close result, which I have not yet been able to reproduce after that. At this point I am wondering whether the results simply do vary this much in between runs (again, all of these plots are already averaged over 10 individual runs each), however, most of the graphs in the paper do look kind of "smooth" compared to my average run.

I hope that this is caused by the SDE rather that another flaw in the generated signal itself.
I will look into that a bit more, but maybe I should be happy and leave it at that for now. 

Thanks again for all your efforts - it's been a great help!

| `scipy.signal.periodogram` | `np.fft.fft` (one of multiple similar runs) | `np.fft.fft` (single clostest run) |
| ---------------------------  | ----------------------------------------- | -------------------------------- |
| ![Fig5Periodo](https://user-images.githubusercontent.com/28440404/106895318-56d64800-66f0-11eb-8ad8-002d5a96f9d2.png) |  ![Fig5MEAN_FFT3](https://user-images.githubusercontent.com/28440404/106915704-9e67ce80-6706-11eb-9dc8-4d9b1455467c.png) | ![Fig5MEAN_FFT](https://user-images.githubusercontent.com/28440404/106908676-cb64b300-66ff-11eb-8fb2-1718d4fd7424.png) |

**Comment by Richert** [comment]
Hi @ffriese 

I believe the differences you observe between the version of David et al. 2003 and yours are merely effects of the randomness in the model (choosing different random seeds can have quite a substantial effect on the PSDs calculated over rather short time intervals) and the PSD calculation itself, rather than differences in the model implementations. 
You can test the latter by choosing different methods of PSD calculation (e.g. Welch's method vs. multitapers) and play around with their meta parameters. This will lead to substantially different PSD profiles.

I suggest to compare the time series for the different w's instead of the PSD shapes to verify your implementation of the multi-population model. And these look pretty much identical to me.

Best, Richard

**Comment by ffriese** [comment]
Dear Richert, I just wanted to let you know, that even though I did not reply for ages, your assessment once again proved to be very helpful, and tuning the parameters of multitapered PSD estimation provides results that are visually much closer to the paper.

Your suggestion that comparing the time-series is a lot more meaningful measure in the first place is, obviously, correct - I just did not feel confident enough to draw a visual conclusion by myself from signals as noisy as these, with my limited experience in the matter. 
And I was less comfortable with building an argument in my thesis on visually deviant results.
Therefore, thanks again for your insights!
